[package]
name = "update_and_notify"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
prometheus = "0.7"
prometheus_exporter = { path = "../.." }
rand = "0.7"
