[package]
name = "simple"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
log = "0.4"
prometheus_exporter = { path = "../.." }
