name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true

      - name: Run clippy
        run: cargo clippy --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set rust version
        run: rustup override set 1.56

      - name: Run tests
        run: cargo +1.56 test --verbose

      - name: Run tests with default features disabled
        run: cargo +1.56 test --no-default-features --verbose

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set rust version
        run: rustup override set 1.56

      - name: Build
        run: cargo +1.56 build --verbose
